[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dscheck-docs"
authors = [{name = "Thomas Cram", email = "tcram@ucar.edu"}]
dynamic = ["version", "description"]
